# Activity 11
## <span style='color:Red'> Name : </span> `Amartyaraj Kumar`
#  <span style='color:Red'> Roll : </span>  `19029` 
#### <span style='color:Red'> Date : </span>  `12/11/22`

# Introduction to TensorFlow

## <span style='color:Green'>Activity 1: </span> `Implementing a Mathematical Equation`

In [1]:
pip install --upgrade pip

     ---------------------------------------- 2.1/2.1 MB 6.5 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 22.2.2
    Uninstalling pip-22.2.2:
      Successfully uninstalled pip-22.2.2
Note: you may need to restart the kernel to use updated packages.


In [1]:
pip install tensorflow

     -------------------------------------- 455.9/455.9 MB 3.5 MB/s eta 0:00:00
     ---------------------------------------- 65.5/65.5 kB 3.7 MB/s eta 0:00:00
     -------------------------------------- 124.6/124.6 kB 7.6 MB/s eta 0:00:00
     -------------------------------------- 895.9/895.9 kB 7.1 MB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 6.7 MB/s eta 0:00:00
     ---------------------------------------- 1.7/1.7 MB 6.7 MB/s eta 0:00:00
     -------------------------------------- 438.7/438.7 kB 6.9 MB/s eta 0:00:00
     ---------------------------------------- 57.5/57.5 kB ? eta 0:00:00
     ---------------------------------------- 3.7/3.7 MB 6.9 MB/s eta 0:00:00
     ---------------------------------------- 5.9/5.9 MB 7.4 MB/s eta 0:00:00
     ---------------------------------------- 42.6/42.6 kB ? eta 0:00:00
     ---------------------------------------- 14.2/14.2 MB 7.1 MB/s eta 0:00:00
     ------------------------------------- 175.4/175.4 kB 10.3

In [2]:
import tensorflow as tf

In [4]:
X=tf.Variable(3)
Y=tf.Variable(4)

In [5]:
C=tf.constant(2)

In [6]:
def myfunc(x,y,c):
    Z=x*x*y+y+c
    return Z

In [7]:
result=myfunc(X,Y,C)
tf.print(result)

42


## <span style='color:Green'>Activity 2: </span> `Matrix Multiplication Using TensorFlow`

In [8]:
X=tf.Variable([[1,2,3],[4,5,6]])
Y=tf.Variable([[7,8],[9,10],[11,12]])

In [9]:
tf.print(X)

[[1 2 3]
 [4 5 6]]


In [10]:
tf.print(Y)

[[7 8]
 [9 10]
 [11 12]]


In [11]:
c1=tf.matmul(X,Y)
tf.print(c1)

[[58 64]
 [139 154]]


In [12]:
c2=tf.matmul(Y,X)
tf.print(c2)

[[39 54 69]
 [49 68 87]
 [59 82 105]]


## <span style='color:Green'>Activity 3: </span> `Reshaping Matrices Using the reshape() Function in TensorFlow`

In [13]:
A=tf.Variable([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16], [17,18,19,20]])

In [14]:
tf.print(A)

[[1 2 3 4]
 [5 6 7 8]
 [9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [16]:
A.shape

TensorShape([5, 4])

In [18]:
tf.print(tf.reshape(A,[5,4,1]))

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]

 [[9]
  [10]
  [11]
  [12]]

 [[13]
  [14]
  [15]
  [16]]

 [[17]
  [18]
  [19]
  [20]]]


In [19]:
A.shape

TensorShape([5, 4])

In [20]:
A = tf.reshape(A,[5,4,1])

In [21]:
A.shape

TensorShape([5, 4, 1])

In [22]:
tf.print(A)

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]

 [[9]
  [10]
  [11]
  [12]]

 [[13]
  [14]
  [15]
  [16]]

 [[17]
  [18]
  [19]
  [20]]]


## <span style='color:Green'>Activity 4: </span> `Implementing the argmax() Function`

In [23]:
X=tf.Variable([[91,12,15], [11,88,21],[90, 87,75]])

In [24]:
tf.print(X)

[[91 12 15]
 [11 88 21]
 [90 87 75]]


In [25]:
X.shape

TensorShape([3, 3])

In [26]:
tf.print(tf.argmax(X,axis=0))

[0 1 2]


In [27]:
tf.print(tf.argmax(X,axis=1))

[0 1 0]


## <span style='color:Green'>Activity 5: </span> `Using an Optimizer for a Simple Linear Regression`

In [28]:
import tensorflow as tf
w=tf.Variable(0.0)
b=tf.Variable(0.0)

In [29]:
def regression(x):
    model=w*x+b
    return model

In [30]:
x=[1,2,3,4]
y=[0,-1,-2,-3]

In [31]:
loss=lambda:abs(regression(x)-y)

In [32]:
optimizer=tf.optimizers.Adam(.01)

In [33]:
for i in range(1000):
    optimizer.minimize(loss,[w,b])

In [34]:
tf.print(w,b)

-1.00371706 0.999803364


In [35]:
tf.print(regression([1,2,3,4]))

[-0.00391370058 -1.00763083 -2.01134801 -3.01506495]


# Regression and Classification Models

## <span style='color:Green'>Activity 6: </span> `Creating an ANN with TensorFlow`

In [36]:
import tensorflow as tf
model = tf.keras.Sequential()

In [38]:
model.add(tf.keras.layers.InputLayer(input_shape=(8,), \
name='Input_layer'))

In [39]:
model.add(tf.keras.layers.Dense(4, activation='relu',
\
name='First_hidden_layer'))
model.add(tf.keras.layers.Dense(1,
name='Output_layer'))

In [40]:
model.variables

[<tf.Variable 'First_hidden_layer/kernel:0' shape=(8, 4) dtype=float32, numpy=
 array([[ 0.03380632, -0.3711094 , -0.09778374,  0.23758161],
        [ 0.65324765, -0.6127907 ,  0.57401854, -0.50358504],
        [-0.7049505 ,  0.16309178,  0.50038236, -0.39459077],
        [ 0.67216986, -0.00566202,  0.5173488 ,  0.6491197 ],
        [ 0.69835037,  0.6676809 ,  0.5859353 ,  0.0272727 ],
        [-0.34816515,  0.53284556,  0.61228305, -0.6861104 ],
        [-0.4673996 ,  0.5500867 ,  0.10452622, -0.68527925],
        [-0.22451052,  0.62958795,  0.26397163,  0.2603898 ]],
       dtype=float32)>,
 <tf.Variable 'First_hidden_layer/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'Output_layer/kernel:0' shape=(4, 1) dtype=float32, numpy=
 array([[ 0.15801549],
        [ 0.64632094],
        [ 1.0149627 ],
        [-0.9763608 ]], dtype=float32)>,
 <tf.Variable 'Output_layer/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [48]:
data = tf.random.normal((32,8))

In [49]:
model.predict(data)

1/1 [==============================] - 0s 43ms/step


array([[-0.7534119 ],
       [ 0.40862477],
       [-1.0003477 ],
       [ 0.3012515 ],
       [ 2.2869735 ],
       [ 0.58293223],
       [ 0.21602638],
       [-1.4903439 ],
       [-0.19946504],
       [ 0.2786739 ],
       [-0.52295446],
       [ 2.5273001 ],
       [-1.5412862 ],
       [ 0.        ],
       [ 0.2360581 ],
       [ 2.0624735 ],
       [ 0.29785728],
       [ 2.1208594 ],
       [ 2.665603  ],
       [ 0.4029443 ],
       [ 1.3464026 ],
       [ 0.12461513],
       [ 2.3253002 ],
       [ 0.779581  ],
       [-0.19167063],
       [ 2.6823916 ],
       [ 0.68106896],
       [-0.7699774 ],
       [ 0.4649785 ],
       [ 1.8580629 ],
       [-0.25737178],
       [ 1.4468434 ]], dtype=float32)

## <span style='color:Green'>Activity 7: </span> `Creating a Linear Regression Model as an ANN with TensorFlow`

In [51]:
import tensorflow as tf
import pandas as pd

In [52]:
df = pd.read_csv('./Activity 11/Datasets/Bias_correction_ucl.csv')
df.head()

station        Date  Present_Tmax  Present_Tmin  LDAPS_RHmin  LDAPS_RHmax  \
0      1.0  2013-06-30          28.7          21.4    58.255688    91.116364   
1      2.0  2013-06-30          31.9          21.6    52.263397    90.604721   
2      3.0  2013-06-30          31.6          23.3    48.690479    83.973587   
3      4.0  2013-06-30          32.0          23.4    58.239788    96.483688   
4      5.0  2013-06-30          31.4          21.9    56.174095    90.155128   

   LDAPS_Tmax_lapse  LDAPS_Tmin_lapse  LDAPS_WS    LDAPS_LH  ...  LDAPS_PPT2  \
0         28.074101         23.006936  6.818887   69.451805  ...         0.0   
1         29.850689         24.035009  5.691890   51.937448  ...         0.0   
2         30.091292         24.565633  6.138224   20.573050  ...         0.0   
3         29.704629         23.326177  5.650050   65.727144  ...         0.0   
4         29.113934         23.486480  5.735004  107.965535  ...         0.0   

   LDAPS_PPT3  LDAPS_PPT4      lat      lon       DEM   Slope  \
0         0.0         0.0  37.6046  126.991  212.3350  2.7850   
1         0.0         0.0  37.6046  127.032   44.7624  0.5141   
2         0.0         0.0  37.5776  127.058   33.3068  0.2661   
3         0.0         0.0  37.6450  127.022   45.7160  2.5348   
4         0.0         0.0  37.5507  127.135   35.0380  0.5055   

   Solar radiation  Next_Tmax  Next_Tmin  
0      5992.895996       29.1       21.2  
1      5869.312500       30.5       22.5  
2      5863.555664       31.1       23.9  
3      5856.964844       31.7       24.3  
4      5859.552246       31.2       22.5  

[5 rows x 25 columns]

In [53]:
df.drop('Date', inplace=True, axis=1)
df.dropna(inplace=True)

In [54]:
target = df[['Next_Tmax', 'Next_Tmin']]
features = df.drop(['Next_Tmax', 'Next_Tmin'],
axis=1)

In [55]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
feature_array = scaler.fit_transform(features)
features = pd.DataFrame(feature_array,
columns=features.columns)

In [56]:
model = tf.keras.Sequential()

In [57]:
model.add(tf.keras.layers.InputLayer\
(input_shape=(features.shape[1],), \
name='Input_layer'))

In [58]:
model.add(tf.keras.layers.Dense(2,
name='Output_layer'))

In [59]:
model.compile(tf.optimizers.RMSprop(0.001),
loss='mse')

In [61]:
tensorboard_callback = tf.keras.callbacks\
.TensorBoard(log_dir="./logs")

In [62]:
model.fit(x=features.to_numpy(),
y=target.to_numpy(),\
epochs=50,
callbacks=[tensorboard_callback])

Epoch 1/50
238/238 [==============================] - 1s 1ms/step - loss: 662.0165
Epoch 2/50
238/238 [==============================] - 0s 2ms/step - loss: 557.5430
Epoch 3/50
238/238 [==============================] - 0s 2ms/step - loss: 462.8298
Epoch 4/50
238/238 [==============================] - 0s 1ms/step - loss: 377.6689
Epoch 5/50
238/238 [==============================] - 0s 2ms/step - loss: 302.0603
Epoch 6/50
238/238 [==============================] - 0s 2ms/step - loss: 236.1071
Epoch 7/50
238/238 [==============================] - 0s 2ms/step - loss: 179.7164
Epoch 8/50
238/238 [==============================] - 1s 2ms/step - loss: 132.8354
Epoch 9/50
238/238 [==============================] - 0s 2ms/step - loss: 95.5889
Epoch 10/50
238/238 [==============================] - 0s 1ms/step - loss: 67.6969
Epoch 11/50
238/238 [==============================] - 0s 1ms/step - loss: 48.5868
Epoch 12/50
238/238 [==============================] - 0s 2ms/step - loss: 35.8947
Epoch

In [63]:
loss = model.evaluate(features.to_numpy(),
target.to_numpy())
print('loss:', loss)

238/238 [==============================] - 0s 1ms/step - loss: 3.6092
loss: 3.609191417694092


## <span style='color:Green'>Activity 8: </span> `Creating a Multi-Layer ANN with TensorFlow`

In [69]:
import tensorflow as tf
import pandas as pd

In [64]:
# load the data
df = pd.read_csv('./Activity 11/Datasets/Bias_correction_ucl.csv')

In [65]:
df.drop('Date', inplace=True, axis=1)
df.dropna(inplace=True)

In [66]:
target = df[['Next_Tmax', 'Next_Tmin']]
features = df.drop(['Next_Tmax', 'Next_Tmin'],
axis=1)

In [67]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

feature_array = scaler.fit_transform(features)
features = pd.DataFrame(feature_array,
columns=features.columns)

In [68]:
model = tf.keras.Sequential()

In [69]:
model.add(tf.keras.layers.InputLayer\
(input_shape=(features.shape
[1],), \
name='Input_layer'))

In [70]:
model.add(tf.keras.layers.Dense(16,
name='Dense_layer_1'))
model.add(tf.keras.layers.Dense(8,
name='Dense_layer_2'))
model.add(tf.keras.layers.Dense(4,
name='Dense_layer_3'))
model.add(tf.keras.layers.Dense(2,
name='Output_layer'))

In [71]:
model.compile(tf.optimizers.RMSprop(0.001),
loss='mse')

In [72]:
tensorboard_callback = tf.keras.callbacks\
.TensorBoard(log_dir="./logs")

In [73]:
model.fit(x=features.to_numpy(),
y=target.to_numpy(),\
epochs=50, callbacks=[tensorboard_callback]
, \
validation_split=0.2)

Epoch 1/50
190/190 [==============================] - 1s 3ms/step - loss: 423.1741 - val_loss: 35.0995
Epoch 2/50
190/190 [==============================] - 0s 2ms/step - loss: 17.2627 - val_loss: 8.5652
Epoch 3/50
190/190 [==============================] - 0s 2ms/step - loss: 6.2625 - val_loss: 5.2382
Epoch 4/50
190/190 [==============================] - 0s 2ms/step - loss: 4.1942 - val_loss: 4.2865
Epoch 5/50
190/190 [==============================] - 0s 2ms/step - loss: 3.4030 - val_loss: 3.9633
Epoch 6/50
190/190 [==============================] - 0s 2ms/step - loss: 2.9888 - val_loss: 3.5797
Epoch 7/50
190/190 [==============================] - 0s 2ms/step - loss: 2.6371 - val_loss: 3.0588
Epoch 8/50
190/190 [==============================] - 1s 3ms/step - loss: 2.3943 - val_loss: 3.2480
Epoch 9/50
190/190 [==============================] - 1s 3ms/step - loss: 2.2182 - val_loss: 2.9126
Epoch 10/50
190/190 [==============================] - 1s 3ms/step - loss: 2.0713 - val_loss: 2.

In [74]:
loss = model.evaluate(features.to_numpy(),
target.to_numpy())
print('loss:', loss)

238/238 [==============================] - 0s 1ms/step - loss: 1.7006
loss: 1.7005542516708374


## <span style='color:Green'>Activity 9: </span> `Creating a Logistic Regression Model as an ANN with TensorFlow`

In [78]:
df = pd.read_csv('./Activity 11/Datasets/qsar_androgen_receptor.csv', sep=';')

In [79]:
df.dropna(inplace=True)

In [80]:
target = df['positive'].apply(lambda x: 1 if
x=='positive' else 0)
features = df.drop('positive', axis=1)

In [81]:
model = tf.keras.Sequential()

In [82]:
model.add(tf.keras.layers.InputLayer\
(input_shape=(features.shape[1],), \
name='Input_layer'))

In [83]:
model.add(tf.keras.layers.Dense(1,
name='Output_layer', \
activation='sigmoid')
)

In [84]:
model.compile(tf.optimizers.RMSprop(0.0001), \
loss='binary_crossentropy',
metrics=['accuracy'])

In [86]:
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir="./logs")

In [87]:
model.fit(x=features.to_numpy(), y=target.to_numpy(),
\

epochs=50, callbacks=[tensorboard_callback]
, \
validation_split=0.2)

Epoch 1/50
43/43 [==============================] - 1s 10ms/step - loss: 0.6926 - accuracy: 0.5282 - val_loss: 0.6186 - val_accuracy: 0.7337
Epoch 2/50
43/43 [==============================] - 0s 4ms/step - loss: 0.6214 - accuracy: 0.7352 - val_loss: 0.5187 - val_accuracy: 0.8728
Epoch 3/50
43/43 [==============================] - 0s 4ms/step - loss: 0.5730 - accuracy: 0.8227 - val_loss: 0.4545 - val_accuracy: 0.9112
Epoch 4/50
43/43 [==============================] - 0s 4ms/step - loss: 0.5387 - accuracy: 0.8494 - val_loss: 0.4092 - val_accuracy: 0.9231
Epoch 5/50
43/43 [==============================] - 0s 4ms/step - loss: 0.5130 - accuracy: 0.8635 - val_loss: 0.3804 - val_accuracy: 0.9260
Epoch 6/50
43/43 [==============================] - 0s 4ms/step - loss: 0.4948 - accuracy: 0.8687 - val_loss: 0.3585 - val_accuracy: 0.9260
Epoch 7/50
43/43 [==============================] - 0s 4ms/step - loss: 0.4795 - accuracy: 0.8702 - val_loss: 0.3443 - val_accuracy: 0.9260
Epoch 8/50
43/43 [=

In [88]:
loss, accuracy = model.evaluate(features.to_numpy(),
\
target.to_numpy())
print(f'loss: {loss}, accuracy: {accuracy}')

53/53 [==============================] - 0s 2ms/step - loss: 0.2792 - accuracy: 0.9093
loss: 0.27924981713294983, accuracy: 0.9092526435852051
